name: ttt-game-server

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # For direct Kafka clients
      - "29092:29092" # For host access if needed
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,
                                            PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,   
                                                    PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  game-service:
    image: ttt-game-service
    container_name: game-service-01
    networks:
      - ttt_game_server_network
  api-gateway:
    image: ttt-api-gateway
    container_name: api-gateway-01
    networks:
      - ttt_game_server_network
    ports:
      - "8080:8080"
      - "9401:9401"
    expose: 
      - 8080
      - 9401
networks:
  ttt_game_server_network: